//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCS.LoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsUserHave", ReplyAction="http://tempuri.org/IService1/IsUserHaveResponse")]
        bool IsUserHave(string sUserName, string sPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsUserHave", ReplyAction="http://tempuri.org/IService1/IsUserHaveResponse")]
        System.Threading.Tasks.Task<bool> IsUserHaveAsync(string sUserName, string sPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTable", ReplyAction="http://tempuri.org/IService1/GetTableResponse")]
        System.IO.MemoryStream GetTable(string sSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTable", ReplyAction="http://tempuri.org/IService1/GetTableResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GetTableAsync(string sSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcuteSql", ReplyAction="http://tempuri.org/IService1/ExcuteSqlResponse")]
        void ExcuteSql(string sSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcuteSql", ReplyAction="http://tempuri.org/IService1/ExcuteSqlResponse")]
        System.Threading.Tasks.Task ExcuteSqlAsync(string sSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsHavePZ", ReplyAction="http://tempuri.org/IService1/IsHavePZResponse")]
        bool IsHavePZ(string YH_GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsHavePZ", ReplyAction="http://tempuri.org/IService1/IsHavePZResponse")]
        System.Threading.Tasks.Task<bool> IsHavePZAsync(string YH_GUID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PCS.LoginService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PCS.LoginService.IService1>, PCS.LoginService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsUserHave(string sUserName, string sPassword) {
            return base.Channel.IsUserHave(sUserName, sPassword);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserHaveAsync(string sUserName, string sPassword) {
            return base.Channel.IsUserHaveAsync(sUserName, sPassword);
        }
        
        public System.IO.MemoryStream GetTable(string sSql) {
            return base.Channel.GetTable(sSql);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GetTableAsync(string sSql) {
            return base.Channel.GetTableAsync(sSql);
        }
        
        public void ExcuteSql(string sSql) {
            base.Channel.ExcuteSql(sSql);
        }
        
        public System.Threading.Tasks.Task ExcuteSqlAsync(string sSql) {
            return base.Channel.ExcuteSqlAsync(sSql);
        }
        
        public bool IsHavePZ(string YH_GUID) {
            return base.Channel.IsHavePZ(YH_GUID);
        }
        
        public System.Threading.Tasks.Task<bool> IsHavePZAsync(string YH_GUID) {
            return base.Channel.IsHavePZAsync(YH_GUID);
        }
    }
}
